.TH "rmqsClientConfiguration_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsClientConfiguration_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool_t \fBIsLittleEndianMachine\fP"
.br
.ti -1c
.RI "\fBrmqsList_t\fP * \fBBrokerList\fP"
.br
.ti -1c
.RI "bool_t \fBUseTLS\fP"
.br
.ti -1c
.RI "\fBrmqsTimer_t\fP * \fBWaitReplyTimer\fP"
.br
.ti -1c
.RI "\fBrmqsLogger_t\fP * \fBLogger\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
