.TH "rmqsBroker_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsBroker_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char_t \fBHostname\fP [RQMS_MAX_HOSTNAME_LENGTH+1]"
.br
.ti -1c
.RI "uint16_t \fBPort\fP"
.br
.ti -1c
.RI "char_t \fBUsername\fP [RQMS_BROKER_MAX_USERNAME_LENGTH+1]"
.br
.ti -1c
.RI "char_t \fBPassword\fP [RQMS_BROKER_MAX_PASSWORD_LENGTH+1]"
.br
.ti -1c
.RI "char_t \fBDBSchema\fP [RQMS_BROKER_MAX_DB_SCHEMA_LENGTH+1]"
.br
.ti -1c
.RI "char_t \fBVirtualHost\fP [RQMS_MAX_HOSTNAME_LENGTH+1]"
.br
.ti -1c
.RI "bool_t \fBUseTLS\fP"
.br
.ti -1c
.RI "char_t \fBAdvicedHostname\fP [RQMS_MAX_HOSTNAME_LENGTH+1]"
.br
.ti -1c
.RI "uint16_t \fBAdvicedPort\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
