.TH "rmqsProperty_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsProperty_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char_t \fBKey\fP [RMQS_MAX_KEY_SIZE+1]"
.br
.ti -1c
.RI "char_t \fBValue\fP [RMQS_MAX_VALUE_SIZE+1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
