.TH "rmqsTuneRequest_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsTuneRequest_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrmqsMsgHeader_t\fP \fBHeader\fP"
.br
.ti -1c
.RI "uint32_t \fBFrameMax\fP"
.br
.ti -1c
.RI "uint32_t \fBHeartbeat\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
