.TH "rmqsLogger_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsLogger_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char_t * \fBFileName\fP"
.br
.ti -1c
.RI "bool_t \fBAppendToFile\fP"
.br
.ti -1c
.RI "FILE * \fBFile\fP"
.br
.ti -1c
.RI "\fBrmqsMutex_t\fP * \fBMutex\fP"
.br
.ti -1c
.RI "\fBrmqsTimer_t\fP * \fBTimer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
