.TH "rmqsMsgHeader_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsMsgHeader_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBSize\fP"
.br
.ti -1c
.RI "uint16_t \fBKey\fP"
.br
.ti -1c
.RI "uint16_t \fBVersion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
