.TH "rmqsThread_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsThread_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_t \fBThreadHandle\fP"
.br
.ti -1c
.RI "ThreadRoutineCallback_t \fBThreadRoutineCallback\fP"
.br
.ti -1c
.RI "CancelIORoutineCallback_t \fBCancelIORoutineCallback\fP"
.br
.ti -1c
.RI "void * \fBParameters\fP"
.br
.ti -1c
.RI "bool_t \fBTerminateRequest\fP"
.br
.ti -1c
.RI "bool_t \fBTerminated\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
