.TH "rmqsProducer_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsProducer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrmqsClient_t\fP * \fBClient\fP"
.br
.ti -1c
.RI "char_t \fBPublisherReference\fP [RMQS_MAX_PUBLISHER_REFERENCE_LENGTH+1]"
.br
.ti -1c
.RI "\fBrmqsTimer_t\fP * \fBPollTimer\fP"
.br
.ti -1c
.RI "uint64_t \fBPublishingIdResultArray\fP [RMQS_PUBLISHING_ID_RESULT_ARRAY_SIZE]"
.br
.ti -1c
.RI "PublishResultCallback_t \fBPublishResultCallback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
