.TH "rmqsList_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsList_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrmqsListNode_t\fP * \fBFirst\fP"
.br
.ti -1c
.RI "size_t \fBCount\fP"
.br
.ti -1c
.RI "ClearDataCallback_t \fBClearDataCallback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
