.TH "rmqsClient_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rmqsClient_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrmqsClientConfiguration_t\fP * \fBClientConfiguration\fP"
.br
.ti -1c
.RI "uint32_t \fBClientMaxFrameSize\fP"
.br
.ti -1c
.RI "uint32_t \fBClientHeartbeat\fP"
.br
.ti -1c
.RI "rmqsClientType_t \fBClientType\fP"
.br
.ti -1c
.RI "void * \fBParentObject\fP"
.br
.ti -1c
.RI "uint32_t \fBCorrelationId\fP"
.br
.ti -1c
.RI "\fBrmqsResponse_t\fP \fBResponse\fP"
.br
.ti -1c
.RI "\fBrmqsBuffer_t\fP * \fBTxQueue\fP"
.br
.ti -1c
.RI "\fBrmqsBuffer_t\fP * \fBRxQueue\fP"
.br
.ti -1c
.RI "char_t \fBRxSocketBuffer\fP [RMQS_CLIENT_RX_BUFFER_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
