.TH "rqmsCreateStreamArgs_t" 3 "Mon Feb 20 2023" "RabbitMQ stream C client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rqmsCreateStreamArgs_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool_t \fBSetMaxLengthBytes\fP"
.br
.ti -1c
.RI "size_t \fBMaxLengthBytes\fP"
.br
.ti -1c
.RI "bool_t \fBSetMaxAge\fP"
.br
.ti -1c
.RI "char_t \fBMaxAge\fP [16]"
.br
.ti -1c
.RI "bool_t \fBSetStreamMaxSegmentSizeBytes\fP"
.br
.ti -1c
.RI "size_t \fBStreamMaxSegmentSizeBytes\fP"
.br
.ti -1c
.RI "bool_t \fBSetQueueLeaderLocator\fP"
.br
.ti -1c
.RI "rqmsStreamLeaderLocator_t \fBLeaderLocator\fP"
.br
.ti -1c
.RI "bool_t \fBSetInitialClusterSize\fP"
.br
.ti -1c
.RI "size_t \fBInitialClusterSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for RabbitMQ stream C client from the source code\&.
